### PR TITLE
chore: unset api id (#64)

### LINKED ISSUE #64: Provide API ID in the API specification

### PR DESCRIPTION
**Pull request by maxim-tschumak**
Reverting #65. Closes #64.

Signed-off-by: Maxim Tschumak <maxim.tschumak@gmail.com>

### CODE REVIEW

**Comment by maxim-tschumak** [comment]
:+1:

**Comment by mikkeloscar** [comment]
:+1:

**Comment by mikkeloscar** [comment]
I created an internal issue to be able to support this fwiw.

**Comment by maxim-tschumak** [comment]
Thanks, @mikkeloscar! it's not highly important (we have a fallback mechanism for APIs with no API ID), but of cause preferable.

**Pull request merged**
