### PR TITLE
Use tokens from PlatformCredentialsSet

### PR DESCRIPTION
**Pull request by aermakov-zalando**
Library updates & minor changes to remove gerry.

### CODE REVIEW

**Comment by harti2006** [comment]
:+1:

**Comment by harti2006** [comment]
We need to update the ACL in AuditTrail API before rolling out this change. This will require to create a new version of the event type.

**Comment by harti2006** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Comment by harti2006** [comment]
:+1:

**Comment by aermakov-zalando** [comment]
👍

**Pull request merged**
